export const landschapsInfo = {
  'Strandwallen en binnenduinrand':`
  Duinen en strandwallen vormen een smalle stook van maximaal 10 km breed langs vrijwel de hele Noordzeekust. Je vindt hier kustduinen, strandwallen en strandvlaktes. De hoogte van de kustduinen varieert tussen ca. 1 en 55m boven NAP. De hoogte van de strandwallen en -vlaktes varieert tussen 2 m boven en 1 m onder NAP. De bodem bestaat uit zeezandgronden, soms verwaaid tot duinen. De strandvlaktes achter de duinen kunnen bedekt zijn met een laag veen en klei, tot een meter dik. Voor de bollenteelt zijn deze vaak weer bedekt met het zand van de afgegraven strandwallen. Onder de duinen ligt een diepe zoetwaterbel, een buffer tegen zoute kwel en een bron voor drinkwater.   `,
  'Zeekleipolders':`
  Zeekleipolders komen voor in Friesland, Groningen, Noord- en Zuid-Holland en Zeeland. Dit landschap is open en vlak en de hoogteligging varieert tussen ongeveer 3 m onder en 1,5 m boven NAP. De hoogtes verschillen lokaal meestal niet meer dan enkele decimeters. Alleen bij de dijken, terpen en wierden kunnen de hoogtes enkele meters verschillen. Zeekleipolders bestaan uit zeekleivlaktes, kreekruggen, kreekbeddingen, terpen en zoetwatergetijdenvlaktes. De bodem bestaat meestal uit zeeklei. Op de kreekruggen is de kleigrond minder zwaar en komt beddingzand ondiep voor. De ondergrond bestaat meestal uit wadafzettingen, maar soms ook uit veen en dekzand. Zeekleipolders zijn meestal sterk ontwaterd. Op enkele natuurgebieden na wordt in zeekleipolders de grondwaterspiegel aangepast aan de landbouw.  `,
  'Laagveen':`
  Laagveen vind je in het Noordelijk kustveengebied langs de randen van het Drents-Fries keileemplateau, het Hollands-Utrechts veengebied en de venige kommen van de Krimpener- en Alblasserwaard in het rivierengebied. Nadat de strandwallen rond 4000 v. Chr. een gesloten kustbarrière vormden, verslechterde de natuurlijke afwatering erachter. Zo ontwikkelde zich een steeds groter veenmoeras. Rond 500 v. Chr. begon de mens het veen af te wateren om het te gebruiken voor landbouw. Hierdoor daalde de bodem. Verder werden door zeespiegelstijging grote stukken veenland weggeslagen of met zeeklei bedekt, denk aan de Zuiderzee en de Biesbosch. Nu is het laagveen een vlak en open landschap met smalle strakke percelen gescheiden door sloten. De veendikte varieert van 7 meter tot minder dan een meter. De hoogteligging varieert tussen 1 m boven en 2 m onder NAP. Naast laagveenvlaktes kent het laagveen ook petgaten: veenplassen die zijn ontstaan bij de vervening van het laagveen. Laagveengebieden worden minimaal drooggelegd om te kunnen gebruiken voor melkveehouderij. Daardoor blijft het veen oxideren en de bodem dalen.  `,
  'Droogmakerijen en IJsselmeerpolders':`
  Droogmakerijen, ook wel drooggelegde veenplassen, komen voor in Noord-Holland, Zuid-Holland en het westen van Utrecht. De eerste drooglegging was de Beemster in 1612. De veenplassen, die ontstaan waren door grootschalige vervening, werden drooggelegd omdat ze een bedreiging vormden voor de steden eromheen. Elke drooglegging leverde bovendien een nieuw stuk vruchtbare landbouwgrond op. Tot dit landschapstype horen ook de Zuiderzeepolders, de Wieringermeer, de Noordoostpolder en Oostelijk en Zuidelijk Flevoland. Het maaiveld ligt in de meeste droogmakerijen tussen 4 en 5,5 m onder NAP. Het hoogteverschil met het omringende landschap kan oplopen tot 5 à 6 m. De bodem bestaat grotendeels uit zeeklei, plaatselijk ook zavel en zand, met soms verslagen veen langs de randen van de droogmakerijen. In alle droogmakerijen wordt water onttrokken voor landbouw en wonen.   `,
  'Overig':`
  
  `,
  'Rivierengebied':`
  Het rivierlandschap is gevormd door afzetting van zand en slib (klei) dat in de afgelopen 11.000 jaar is aangevoerd door de Rijn en de Maas. Kenmerkend aan het landschap is de afwisseling van stroomruggen en laaggelegen rivierkommen. Rivierkommen zijn vlaktes die regelmatig overstroomden voordat er dijken waren. Vanaf de 11e eeuw zijn er dijken aangelegd. Sindsdien slibben alleen de uiterwaarden nog op en komt het binnendijkse landschap relatief steeds lager te liggen. Zonder maatregelen zou het overstromingsrisico hierdoor toenemen. Het rivierlandschap bestaat uit stroomruggen of oeverwallen, rivierkommen, restgeulen, uiterwaarden en overslaggronden. 
  `,
  'Rivierterrassen':`
  Rivierterrassen van Rijn en Maas komen voor langs de oostgrens van de Achterhoek en de Liemers, aan weerszijden van de Maas in Noord- en Midden-Limburg en in oostelijk Noord-Brabant. Het landschap kenmerkt zich door diverse terrasniveaus van verschillende hoogtes. Het heeft een zwak golvend reliëf met veel restgeulen van de Rijn en de Maas, waarin nu beken stromen zoals de Niers, de Tungelroyse Beek in Midden-Limburg en de Groote Molenbeek bij Wanssum. Het rivierterrassenlandschap ligt globaal tussen 10 en 30 m boven NAP. Rivierterrassen bestaan uit zandige en kleiige terrassen, rivierduinen, restgeulen en riviervlaktes. Rivierduinen kunnen tot meer dan 15 m boven terrassen uitsteken. Ook komen landschapseenheden uit andere landschapstypes voor, zoals dekzandruggen, stuifzanden, beekdalbodems, veenvlaktes en droogdalen. De bodem bestaat uit oude rivierkleigronden op een pakket zand en grind van 10 tot 50 m dik. De zandige ondergrond is goed doorlatend. Restgeulen langs terrasranden worden gevoed door kwel vanuit hogere terrassen.
In dit landschapstype wordt onderscheid gemaakt tussen zandige- en kleiige terrassen, rivierduinen, restgeulen en riviervlakten. Rivierduinen kunnen tot meer dan 15 m boven terrassen uitsteken. Ook komen landschapseenheden uit de andere landschapstypen voor, zoals dekzandruggen, stuifzanden, beekdalbodems, veenvlakten en droogdalen. De bodem bestaat uit oude rivierkleigronden op een 10 tot 50 m dik pakket zand en grind. De zandige ondergrond is goed doorlatend. Restgeulen langs terrasranden worden gevoed door kwel vanuit hoger gelegen terrassen.
  `,
  'Stuwwallen':`
  Het stuwwallandschap komt voor in Midden- en Oost-Nederland en is ontstaan in de voorlaatste ijstijd, toen het landijs Nederland bereikte en oudere rivierafzettingen opstuwde. Het reliëf is zwak golvend, afgewisseld door steile hellingen en vlakke delen. De hoogteligging varieert van enkele meters boven NAP in het Gooi tot boven 100 m boven NAP op de zuidelijke Veluwezoom. Dit landschapstype bestaat naast stuwwallen uit sandrs of spoelzandwaaiers, daluitspoelingswaaiers, droogdalen, essen en gestuwde grondmorene. Delen van de stuwwal zijn bedekt met dekzand en stuifzand (uit het dekzandlandschap). Op de zuidoost hellingen van de Veluwezoom en stuwwal van Nijmegen ligt löss. De bodem bestaat overwegend uit goed doorlatende, droge, arme zandgronden, en de ondiepe ondergrond uit gestuwd rivierzand, -grind en leem. De gestuwde afzettingen kunnen meer dan 100 m dik worden. De ondiepe ondergrond in de stuwwallen van Ootmarsum en Oldenzaal bestaat uit gestuwde keileem en zand en klei van oudere afzettingen. Door het ondoorlatende karakter van de ondergrond komen hier veel beekdalen (uit het dekzandlandschap) voor. 
    `,
  'Keileemgebied':`
  Het keileemlandschap komt voor in Noordoost-Nederland, Drenthe, Oost-Groningen, Twente, Friesland, op Texel en Wieringen en in de Noordoostpolder. Keileem is een mengsel van stugge leem met grof zand en stenen. Dit mengsel is in de voorlaatste ijstijd in een dikke laag van 1 tot 10 meter onder de ijskap afgezet. Daarna is de keileem overstoven met dekzand, zijn beekdalen diep ingesneden en zijn grote oppervlakten bedekt geraakt met veen. Het landschap heeft een zwak golvend reliëf, maar op het Drents-Fries plateau komen ook gebieden voor die zeer vlak zijn. Naast keileemruggen en keileemvlaktes komen ook elementen uit het dekzand- en laagveenlandschap voor, zoals beekdalbodems, dekzandvlaktes, dekzandruggen en veenvlaktes. Door de complex genese van het keileemlandschap is de samenstelling van bodem en ondergrond en de hydrologische situatie zeer variabel. Het slecht doorlatende karakter van de keileem kan stagnatie van grondwater veroorzaken waardoor lokaal natte omstandigheden overheersen.
  `,
  'Dekzandgebied':`
  Het dekzandlandschap komt verspreid voor in Midden-, Noordoost-, en Zuid-Nederland. Het is gevormd in de laatste ijstijd onder invloed van wind en smeltwater. Het strekt zich uit over de relatief lage delen van Nederland die niet bedekt zijn geraakt met rivierklei, zeeklei of veen. Kenmerkend voor het landschap is de afwisseling van dekzandruggen, -vlaktes en slingerende beken en het vaak kleinschalige karakter. De hoogteligging varieert van rond 0 m tot meer dan 30 m boven NAP. De lokale hoogteverschillen zijn zelden meer dan enkele meters, met uitzondering van de stuifzandgebieden. Het dekzandlandschap bestaat uit dekzandruggen dekzandvlaktes, stuifzandduinen, zandige- en venige beekdalbodems, depressies met en zonder veen, veenvlaktes en essen rond de oude dorpen. De bodem bestaat uit leemarme tot sterk lemige zandgronden. De dikte van het dekzanddek en de opbouw van de ondiepe ondergrond kan erg verschillen: zo komen in de Roerdalslenk in Noord-Brabant dekzandpakketten tot 50 m dik voor, maar op de hoger gelegen landsdelen zoals de Peelhorst en Twente is het dekzand maar enkele meters dik. Verder is er ook veel variatie in droge en natte grond: lemige laaggelegen natte zandgronden en droge leemarme zandgronden komen naast elkaar voor.
  `,
  'Voormalige hoogvenen':`
  De voormalige hoogvenen van Noordoost-Nederland en de Brabant-Limburgse Peel zijn vlakke open agrarische landschappen met rechte lijnen (rationele verkaveling). De bodem bestaat uit zand met een laag teruggestort veen, als gevolg van de veenafgravingen voor turfwinning. Het veen is met zand verwerkt om het geschikt te maken voor landbouw. Resten hoogveen torenen meters boven het omringende landschap uit, zoals in het natuurgebied de Engbertsdijkvenen. Door lage grondwaterstanden en de bodem die slecht vocht vasthoudt, zijn deze gebieden kwetsbaar voor verdroging. In droge periodes kunnen organische stof en zand verstuiven. Om de droogte te bestrijden, wordt er naar deze gebieden veel water aangevoerd via de oude turfvaarten en kanalen.   `,
  'Heuvelland en lossgebied':`
  Heuvelland-lössgebied ligt in het zuidelijk deel van de provincie Zuid-Limburg. Het is een reliëfrijk heuvellandschap met grote hoogteverschillen, van ongeveer 45 m boven NAP in het Maasdal bij Maastricht tot ruim 320 m boven NAP op de Vaalserberg. In dit landschap komen lössplateaus, -terrassen, -hellingen, kalkhellingen, droogdalen en beekdalbodems voor. De bodem bestaat vooral uit een dikke laag löss: leem dat door de wind is aangevoerd. De löss ligt op een pakket zand en grind dat in verschillende terrasniveaus is afgezet door de Maas. Daaronder ligt kalksteen. Het grondwater ligt hier heel diep onder het maaiveld. Je vindt hier diep ingesneden beekdalen, zoals de Geul, Gulp, Selzerbeek, Eyserbeek, Noorbeek en de Voer. Slechts door enkele hiervan stroomt water. Lössgronden blijven in droge periodes lang vocht vasthouden, maar kunnen neerslag niet snel opnemen. Daardoor zijn de hellingen gevoelig voor bodemerosie.
    `,
  '':''
}