export const landschapsInfo = {
  'Strandwallen en binnenduinrand':`
  Duinen en strandwallen vormen een smalle stook van maximaal 10 km breed langs vrijwel de hele Noordzeekust; onze natuurlijke kustverdediging. Binnen dit landschapstype onderscheiden we drie subtypen: kustduinen, strandwallen en strandvlakten. De lokale hoogteverschillen binnen de kustduinen variëren van ca. 1 tot 55m +NAP. De strandwallen en -vlakten hebben een hoogte tussen 2 m +NAP en 1 m – NAP. De bodem bestaat uit zeezandgronden al dan niet verwaaid tot duinen. De strandvlakten achter de duinen kunnen bedekt zijn met een laag veen en klei, tot een dikte van een meter dik. Ten behoeve van de bollenteelt zijn deze vaak weer bedekt met het zand van de afgegraven strandwallen. Onder de duinen ligt een diepe zoetwaterbel, een buffer tegen zoute kwel en een bron voor drinkwater.  
  `,
  'Zeekleipolders':`
  Het zeekleilandschap komt voor in Friesland en Groningen, Noord-, en Zuid-Holland en Zeeland. Het polderlandschap is open en vlak en de hoogteligging varieert tussen ongeveer 3 m - NAP en 1,5 m + NAP. De lokale hoogteverschillen bedragen zelden meer dan enkele decimeters, behalve bij de dijken, terpen en wierden waar het hoogteverschil enkele meters kan bedragen. In dit landschap onderscheiden we zeekleivlakten, kreekruggen, kreekbeddingen, terpen en zoetwatergetijdenvlakten. De bodem bestaat meestal uit zeeklei. Op de kreekruggen is de kleigrond minder zwaar en komt beddingzand ondiep voor. De ondergrond bestaat meestal uit wadafzettingen, maar ook veen komt voor, of aan de randen van dit landschapstype: dekzand. Het zeekleipolder zijn over het algemeen goed ontwaterd. Op enkele natuurgebieden na wordt in dit hele landschap een grondwaterspiegel in stand gehouden die is gericht op het uitvoeren van landbouw.
  `,
  'Laagveen':`
  Tot het laagveenlandschap behoort het Noordelijk kustveengebied langs de randen van het Drents-Fries keileemplateau, het Hollands-Utrechts veengebied, en de venige kommen van de Krimpener- en Alblasserwaard in het rivierengebied. Nadat de strandwallen ca. 4000 v. Chr. een gesloten kustbarrière vormden, verslechterde de natuurlijke afwatering er achter en ontwikkelde zich een groot veenmoeras. Rond 500 v. Chr. bereikte het zijn grootste verbreiding. Vanaf die periode begint de mens het veen te afwateren om er landbouw op te bedrijven met als gevolg dat de bodem daalt. Onder invloed van een stijgende zeespiegel worden grote stukken veenland (Zuiderzee, Biesbosch) weggeslagen of met zeeklei bedekt. Wat restte is het huidige vlakke en open laagveenlandschap met zijn typische cope-ontginningpatroon van smalle opstrekkende percelen gescheiden door sloten. De veendikte varieert van 7 meter in het hart van Hollands-Utrechts veengebied tot minder dan een meter op de flanken van de hogere zandgronden. De hoogteligging varieert tussen 1 m +NAP en 2 m – NAP. Landschapseenheden binnen het laagveen zijn laagveenvlakte en petgaten, ontstaan bij de vervening van het laagveen. Laagveengebieden worden doorgaans gebruikt voor melkveehouderij. Door de waterbeheerder wordt hiervoor een minimale drooglegging in stand gehouden. De veenoxidatie en dus de bodemdaling gaat in dit gebied dus nog steeds door. 
  `,
  'Droogmakerijen en IJsselmeerpolders':`
  Droogmakerijen komen voor in Noord-Holland, Zuid-Holland, het westen van Utrecht. Het zijn drooggemalen veenplassen die door grootschalige vervening zijn ontstaan. De eerste drooglegging was de Beemster in 1612. De veenmeren werden drooggelegd omdat zij een bedreiging vormde voor de steden in het omliggende veenland. Elke drooglegging leverde bovendien nieuw areaal vruchtbare landbouwgrond op. De Zuiderzeepolders kunnen we ook tot dit landschapstype rekenen, evenals de Wieringermeer, de Noordoostpolder en Oostelijk en Zuidelijk Flevoland. Het maaiveld ligt in de meeste droogmakerijen tussen de 4 tot 5,5 m -NAP. Het hoogteverschil met de omringende landschappen kan oplopen tot 5 á 6 m. De bodem bestaat voor het merendeel uit zeeklei, plaatselijk ook zavel en zand met langs de randen van de droogmakerijen lokaal (verslagen) veen. Alle droogmakerijen worden permanent bemalen om voldoende drooglegging landbouw en wonen te garanderen.  
  `,
  'Overig':`
  
  `,
  'Rivierengebied':`
  Het Rivierlandschap is gevormd door afzetting van zand en slib (klei) dat in de afgelopen 11.000 jaar is aangevoerd door de Rijn en de Maas. Het rivierlandschap wordt gekenmerkt door een afwisseling van stroomruggen en laaggelegen rivierkommen. Rivierkommen zijn vlaktes die regelmatig overstroomden voordat er dijken waren. Vanaf de 11e eeuw zijn er dijken aangelegd. Sindsdien slibben alleen de uiterwaarden nog maar op en komt het binnendijkse landschap relatief steeds lager te liggen. Zonder maatregelen zou het overstromingsrisico hierdoor toenemen. Binnen het rivierlandschap komen de volgende eenheden voor: stroomrug of oeverwal, rivierkom, restgeul, uiterwaard en overslaggrond. 
  `,
  'Rivierterrassen':`
  Rivierterrassen van Rijn en Maas komen voor langs de oostgrens van de Achterhoek en de Liemers tot weerszijden de Maas in Noord- en Midden-Limburg en oostelijk Noord-Brabant. Het landschap kenmerkt zich door diverse terrasniveaus met een verschillende hoogteligging. Dit gebied kent een zwak golvend reliëf met veel restgeulen van de Rijn en de Maas, waarin nu beken stromen zoals de Niers, de Tungelroyse Beek in Midden-Limburg, de benedenloop van de Geleenbeek bij Susteren en de Groote Molenbeek bij Wanssum. Het rivierterrassenlandschap ligt globaal tussen 10 en 30 m +NAP. 

In dit landschapstype wordt onderscheid gemaakt tussen zandige- en kleiige terrassen, rivierduinen, restgeulen en riviervlakten. Rivierduinen kunnen tot meer dan 15 m boven terrassen uitsteken. Ook komen landschapseenheden uit de andere landschapstypen voor, zoals dekzandruggen, stuifzanden, beekdalbodems, veenvlakten en droogdalen. De bodem bestaat uit oude rivierkleigronden op een 10 tot 50 m dik pakket zand en grind. De zandige ondergrond is goed doorlatend. Restgeulen langs terrasranden worden gevoed door kwel vanuit hoger gelegen terrassen.
  `,
  'Stuwwallen':`
  Het stuwwallandschap komt voor in Midden- en Oost-Nederland, ontstaan in de voorlaatste ijstijd, de periode dat het landijs Nederland bereikte en oudere rivierafzettingen opstuwde. Het reliëf is zwak golvend, afgewisseld door steile hellingen en vlakke delen. De hoogteligging, varieert van enkele meters boven NAP in het Gooi tot boven de 100 m +NAP op de zuidelijke Veluwezoom. De volgende landschapseenheden komen voor: stuwwallen, sandrs of spoelzandwaaiers, daluitspoelingswaaiers, droogdalen, essen en gestuwde grondmorene. Uit het dekzandlandschap komen dekzandruggen en beekdalen en stuifzanden voor. De bodem bestaat overwegend uit goed doorlatende, droge, arme zandgronden (podzolgronden) en de ondiepe ondergrond uit gestuwd rivierzand, -grind en leem. De gestuwde afzettingen kunnen een dikte van meer dan 100 m bereiken. Delen van de stuwwal zijn bedekt met dekzand en stuifzand en op de zuidoosthellingen van de Veluwezoom en stuwwal van Nijmegen ligt löss. De ondiepe ondergrond In de stuwwallen van Ootmarsum en Oldenzaal bestaat gestuwde keileem en zand en klei van oudere afzettingen. Door het ondoorlatende karakter van de ondergrond komen hier veel beekdalen voor. 
  `,
  'Keileemgebied':`
  Het keileemlandschap komt voor in noordoost Nederland, in Drenthe, Oost-Groningen en Twente maar ook in Friesland, op Texel en Wieringen en in de Noordoostpolder. Keileem is een mengsel van stugge leem met grof zand een stenen dat in een 1 tot 10 meter dikke laag in de voorlaatste ijstijd onder de ijskap afgezet. Daarna is de keileem overstoven met dekzand, zijn beekdalen diep ingesneden en zijn grote oppervlakten bedekt geraakt met veen. Het landschap heeft een zwak golvend reliëf, maar op het Drents-Fries plateau komen ook gebieden voor die zeer vlak zijn. Naast keileemruggen en keileemvlakten kenmerkend voor dit landschapstype, komen ook subtypen uit het dekzand- en laagveenlandschap voor zoals beekdalbodems, dekzandvlakten, dekzandruggen en veenvlakten. Door de complex genese van keileemlandschap is de samenstelling van de bodem en de ondergrond, en de hydrologische situatie zeer variabel. Het slecht doorlatende karakter van de keileem kan stagnatie van grondwater veroorzaken waardoor lokaal natte omstandigheden overheersen. 
  `,
  'Dekzandgebied':`
  Het dekzandlandschap komt verspreid voor in een aantal grote gebieden in Midden-, Noordoost, en Zuid-Nederland . Het landschap is gevormd in de laatste ijstijd onder invloed van wind en smeltwater en strekt zich uit over de relatief lage delen van Nederland die niet bedekt zijn geraakt met rivier- of zeeklei of veen. Kenmerkend voor het landschap is de afwisseling van dekzandruggen, -vlakten en slingerende beken en het overwegend kleinschalige karakter. De hoogteligging varieert van rond 0 m NAP tot meer dan 30 m NAP in Twente en Limburg. De lokale hoogteverschillen zijn zelden meer dan enkele meters, met uitzondering van de stuifzandgebieden. De volgende landschapseenheden komen voor: dekzandruggen dekzandvlakten, stuifzandduinen, zandige- en venige beekdalbodems, depressies met en zonder veen, veenvlakten en essen rond de oude dorpen. De bodem bestaat uit leemarme tot sterk lemige zandgronden. De dikte van het dekzanddek en de opbouw van de ondiepe ondergrond zijn zeer variabel en hangen af van de genese van de verschillende gebieden binnen het zandgebied. In de Roerdalslenk in Noord-Brabant komen dekzandpakketten tot 50 m dik voor. Op de hoger gelegen landsdelen zoals de Peelhorst en Twente is de laag dekzand maar enkele meters dik. Hydrologisch gezien is het landschap ook zeer gevarieerd, en komen lemige laaggelegen natte zandgronden en droge leemarme zandgronden op ruggen naast elkaar voor.
  `,
  'Voormalige hoogvenen':`
  De voormalige hoogveenlandschappen van Noordoost-Nederland en de Brabant-Limburgse Peel zijn vlakke open agrarische landschappen met een rationele verkaveling . De bodem bestaat als gevolg van de afgravingen van het veen voor de turfwinning uit zand met een in dikte wisselende laag teruggestort veen. Door bodembewerking is het veen met het zand verwerkt tot een voor landbouw geschikte bouwvoor. Resten hoogveen zoals bijvoorbeeld het natuurgebied de Engbertsdijkvenen torenen meters boven het omringende landschap uit. Lage grondwaterstanden en het geringe vochthoudende vermogen van bodem maakt dat deze gebieden kwetsbaar zijn voor verdrogen. In droge perioden kunnen organische stof en zand verstuiven. Om de droogte te bestrijden wordt via het stelsel van oude turfvaarten en kanalen naar deze gebieden veel water aangevoerd.  
  `,
  'Heuvelland en lossgebied':`
  Heuvelland-lössgebied ligt in het zuidelijk deel van de provincie Zuid-Limburg. Het is een reliëfrijk heuvellandschap met voor Nederlandse begrippen grote hoogteverschillen, van ongeveer 45 m +NAP in het Maasdal bij Maastricht tot ruim 320 m +NAP op de Vaalserberg. In dit landschap komen lössplateaus,- terrassen, -hellingen, kalkhellingen, droogdalen en beekdalbodems voor. De bodem bestaat veelal uit een dikke laag löss, door de wind aangevoerde leem. De löss ligt op een pakket zand en grind dat in verschillende terrasniveaus is afgezet door de Maas. Daaronder ligt kalksteen die in veel steile hellingen is ontsloten. Het grondwater bevindt zich hier op grote diepte onder het maaiveld. Slechts enkele diep ingesneden beekdalen (Geul, Gulp, Selzerbeek, Eyserbeek, Noorbeek en de Voer) zijn watervoerend. Lössgronden blijven in droge perioden lang vocht vasthouden, maar kunnen neerslag niet snel opnemen waardoor de hellingen gevoelig zijn voor bodemerosie. 
  `
}